### ISSUE TITLE
Getit problem on my 10.2.3

### ISSUE THREAD

**Issue by limelect** [corneliusdavid/AutoGetIt#1]
Get it does not work on my 10.2.3 since day 1.
Using 10.2.1 (on my backup) it worked somehow
I was expecting to see  getit in you're program the getit components
so I will finally use it.
Pressing the refresh button a few times gets an error doscmnd as expected.
However, waiting for 1/2 an hour did nothing except the error (refresh).

I wander AFTER running your program pressing getit on the IDE  did not bring
an error but it turns endlessly.

P.S on line    if StartsText('--', ANewLine) then
ANewLine='GetIt Package Manager - Version 6.0'
Making this line // it brings back as though the getit program does not work
Is it possible that getit on 10.2 works differently?
![Screenshot - 27_02_2021 , 19_36_04](https://user-images.githubusercontent.com/4199131/109395066-12c31580-7933-11eb-93e3-deef930d37ec.jpg)

**Comment by corneliusdavid** [comment]
Delphi 10.4 comes with GetIt 7.0, which evidently has a more commands: 
![image](https://user-images.githubusercontent.com/4973808/109408881-8caecb00-7942-11eb-9b2c-302af9b23b1a.png)

I will do some research with other versions and see what I can do about providing support for them.

**Comment by corneliusdavid** [comment]
It gets more complicated. Delphi 10.3 Rio also comes with GetItCmd 7.0 but some of the commands are incompatible with Delphi 10.4's GetItCmd 7.0's commands:

![image](https://user-images.githubusercontent.com/4973808/109409077-43f81180-7944-11eb-8b6d-a47be5cb5f6f.png)

**Comment by limelect** [comment]
Are there not common basic commands used in all?
So one can use only those?
maybe no need for first-time >>> StartsText('--' or a different approch

**Comment by corneliusdavid** [comment]
Not in the GetItCmd.exe utility. There is an API but I don't have information to that (yet). The GetIt Package Manager in the Delphi IDE works within that version of Delphi but the command-line tool has not received much attention. I'm finding the environment variables affect it, too.

**Comment by limelect** [comment]
Took off   if StartsText('--', ANewLine) then
changed CmdLineArgs :='-listavailable';
It is a start
![Screenshot - 28_02_2021 , 10_37_36](https://user-images.githubusercontent.com/4199131/109412529-2d3bd400-79b1-11eb-87c5-40ed76261002.jpg)

However, I have a new problem-related to DosCommand i think
once i run the program the IDE compile with errors i have to reload Delphi.

**Comment by corneliusdavid** [comment]
Yes, but then the package count is off and a right+click to install one could lead to trying to install a package with the name, "--".  I'm fixing that right now...

**Comment by corneliusdavid** [comment]
The problem is that older versions of GetItCmd have different commands--it's not the check for "--" at the start.  I put that back and and updated the code to support a couple of versions back with different command arguments. Try this update.

It's also important to have the path set properly.  If you have multiple versions of Delphi installed, the first Delphi path may point to a different version of GetIt than the one you want to run.

If you have any more problems, I'll have to look at them later--or wait until I get information from Embarcadero on GetIt's API.
