### ISSUE TITLE
API third party components 

### ISSUE THREAD

**Issue by izac3d** [corneliusdavid/AutoGetIt#10]
Hi David,

I am testing the API version but I was hoping that you avoid using third part components. I need Doscommand, raize components for a url label ?

And what are  Beyond.Bind.Json, Beyond.Bind.StrUtils belong to ? I can not find results from google.

**Comment by corneliusdavid** [comment]
First, remember this branch is still under development (I haven't had time to work on it in about a month) and is quite a ways from working.

Look at the README for the project under "Dependency" to find a link to custom LiveBinding methods. DosCommand and Raize Components (renamed Bonus KSVC) are in GetIt.  I will update the README to include these.

There are no commercial components used in this project.

**Comment by izac3d** [comment]
I am sick but I would like to try to help, can I ?

**Comment by corneliusdavid** [comment]
That would be great! You have already forked the project, so as you make local updates, submit pull requests for me to merge in.

The last thing I was working on is getting details in the side panel and and main control list but paused to add another custom LiveBindings method. I think I have a few pending changes that are not checked in--I'll try to get them in over the next day or so.
