### ISSUE TITLE
Remove extra linefeeds from list

### ISSUE THREAD

**Issue by StefanGrube** [corneliusdavid/AutoGetIt#12]
Hi, thanks for this very helpful und easy to use tool!
When I download the list of packages for D11/Alexandria there are currently 6 extra entries with only text, that seem to come from extra linefeeds in the package description. Here's an example:
  "VirtualTreeView-2021.09-11                         2021.09         Delphi and CBuilder treeview control. It is one of the most flexible and advanced tree controls available today. Supported on platforms: Windows."
  "Please, ensure that previous versions of VirtualTree are not installed before installing this library."
It's pretty easy to avoid that with adding just another condition to the procedure DosCommandNewLine():
  "else if not FFinished and (Trim(ANewLine).Length > 0) then"
  ->
  "else if ((not FFinished) and (Trim(ANewLine).Length > 0) and (ANewLine.Contains('  '))) then"
Then only entries are added if they contain a double space as separator for the different columns.

**Comment by corneliusdavid** [comment]
Thanks for pointing this out--and for a proposed fix.  I'll look at this in a day or two.

**Comment by corneliusdavid** [comment]
Sorry it took me so long to get to this but thanks again for reporting this. I added the additional check and it fixed extra lines for five entries.
