### ISSUE TITLE
Progress displayed wrong of no packaged checked for downloading

### ISSUE THREAD

**Issue by MHumm** [corneliusdavid/AutoGetIt#14]
If you do not check any packages but still click the "Install checked" button the progress window claims that 0 of 2 packages are installed. The 2 seems a bit odd there... ;-)

...other than that: that tool's a good idea!

**Comment by corneliusdavid** [comment]
Oops!  The "0 of 2" is what is set at design-time; in the case of no packages selected, the form is never updated because it finishes before it starts!  Thanks for pointing this out--it'll be fixed in the next commit.
