### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by jr-ch** [corneliusdavid/AutoGetIt#18]
No way to compile the source.

Compiling is required as every Delphi Version has to be included into the source. Even Delphi 12 is already in the code, the code isn't working. Even if you create a new project with just the code it always gives the error of "AutogetitVCL.dres" not found. This file (Delphi graphic compiles ressource) is missing.

**Comment by corneliusdavid** [comment]
A `.dres` file is a compiled resource, not needed for building the project (see the [DocWiki page on File Extensions](http://docwiki.embarcadero.com/RADStudio/Athens/en/File_Extensions_of_Files_Generated_by_RAD_Studio)).

I have pulled this project straight from Github onto a new computer (or VM) and built it without any problems. The only thing you need first is to install the [DOSCommand](https://github.com/TurboPack/DOSCommand) components.

**Comment by jr-ch** [comment]
Hi David

Unfortunatly there is a reference to some “*.dres” file in the Delphi-Project (dpr) Source. And this prevents the compile. Also the doscommand no longer works as in the past (tried to run it after removing the “dres” from the project-file. After removing of the reference to the “dres” it could be built. But the execution of getit then never brings any resultset back.

The problem is the version of Doscommand. I’m using the actual one (2024) on getit.

Actually I’m on a new fork of the project.

I have added “DosCommand.OutputLines := lbPackages.Items;” after the Doscommand.Execute to make things easier (see also here: https://github.com/TurboPack/DOSCommand/blob/master/Demo/Unit4.pas)

Btw: I tried to compile with Delphi11.3 (actually my working environment and also with Delphi12). Both in the Enterprise edition. On different machines.

**Comment by jr-ch** [comment]
Ok, no wit works.

The problem was the Doscommand-package. I removed it from the source and removed also the requirement in the project options. Then I placed it again on the form, assigned all stuff (events) and after that I had also to reassign all icon-stuff and then bumm….compile done. 

And app is also working. Great!

It worked in the past and now also for Delphi 12.

**Comment by corneliusdavid** [comment]
Excellent; glad you figured it out!
