### ISSUE TITLE
List index out of bounds

### ISSUE THREAD

**Issue by birbilis** [corneliusdavid/AutoGetIt#19]
![image](https://github.com/corneliusdavid/AutoGetIt/assets/3461504/c592920f-403e-453f-9a1b-3e54055bdd28)

If I type something as filter text and refresh package list, then there is no row selected (as expected - results might be empty anyway)

This will cause a list index out of bounds though if I right click in the empty space and then click again in it (outside of the popup / context menu). Probably tries to restore previously selected row and doesn't handle case where there was no selected row

**Comment by corneliusdavid** [comment]
Thanks!  Fix pushed.
