### ISSUE TITLE
still does not work

### ISSUE THREAD

**Issue by limelect** [corneliusdavid/AutoGetIt#2]

**Comment by limelect** [comment]
as is does not work on 10.2.3 took off -----
further more each run i have to delete
"for the project to compileThe imported project file could not be loaded. 'Edition' is an unexpected token. The expected token is '='. Line 69, position 28.  C:\Users\LimElect\AppData\Roaming\Embarcadero\BDS\19.0\environment.proj"<<<<<<<<
![Screenshot - 28_02_2021 , 11_17_40](https://user-images.githubusercontent.com/4199131/109413528-9c67f700-79b6-11eb-98f0-f5049326f8f3.jpg)

**Comment by corneliusdavid** [comment]
You will have to make do with the project as it is--feel free to modify it and if you get it to work, make a pull request with your update. You can also modify the batch files files for your own use. I hope to eventually replace the clunky and inconsistent command-line utility with an API which should make all of these issues go away.
