### ISSUE TITLE
List all packages that have updates

### ISSUE THREAD

**Issue by birbilis** [corneliusdavid/AutoGetIt#20]
How can I list all packages that have updates?

Not sure if possible, there is some lengthy info here that might be helpful but seems too long an article to bother:
https://blogs.embarcadero.com/streamlining-rad-studio-upgrades-with-getit

Update all packages using the GetIt Package Manager from the command line (haven't tried if accurate): https://sl.bing.net/h1O77QAKlbw

If using GetIt command line tool under the hood probably it can return list of available updates so that one can opt to try to update all or uncheck some and proceed to update?

**Comment by birbilis** [comment]
update: seems ChatGPT/Bing was hallucinating in claiming there is --update=all param at getitcmd

**Comment by corneliusdavid** [comment]
Yeah, that'd be cool but not available from the cmd-line.  Might be from the API version--if I can ever get to it.

I always wished there was a filter for _not_ installed; seems like it'd be much more useful than showing what you already have installed.
