### ISSUE TITLE
D10.2

### ISSUE THREAD

**Issue by limelect** [corneliusdavid/AutoGetIt#21]
D10.2.3
Can you return to the old ver that worked on my Delphi? with the new modifications
It does not even load
The main page does not load

**Comment by corneliusdavid** [comment]
This code was written in Delphi 10.4, never compiled in Delphi 10.2. It uses the ImageCollection component which was introduced in 10.3; therefore, it will not work in anything earlier.

However, if you click on [Releases](https://github.com/corneliusdavid/AutoGetIt/releases), it will allow you to download a pre-compiled executable and that will support versions of Delphi back to 10.2.

I've updated the README for this repository with this information and will consider this issue closed.
