### ISSUE TITLE
Pressing refresh twice

### ISSUE THREAD

**Issue by limelect** [corneliusdavid/AutoGetIt#3]
Pressing the refresh button twice gave "DosCommand still running"
so I added

   DosCommand.Execute;
    repeat
      Application.ProcessMessages;
    until FFinished;
    DosCommand.Stop;<<<<<<<<<<<<<<<<<<<<
    CleanPackageList;

**Comment by corneliusdavid** [comment]
my preferred method is to disable the possibility of refreshing in the first place...

```
actRefresh.Enabled := False;
try
  // refresh code
finally
  actRefresh.Enabled := True;
end;
```

I committed that change.
