### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by dfilteau** [corneliusdavid/AutoGetIt#4]
Compiled in 32-bit Windows platform using Delphi 10.4 (Version 27.0.38860.1461) and running in Admin mode, I'm getting the following error in the Demo2 application when I click the "Refresh Package List" button:

> "Access violation at address 0040A35A in module 'AutoGetItVCL.exe', Write of address 00000044."

I'm probably missing something here but any suggestion outside of the likes of "get a life" and "learn to code" would be appreciated.

TIA!

**Comment by corneliusdavid** [comment]
I've upgraded to Delphi 10.4.2 (27.0.40680.4203) so can't exactly reproduce your environment.

What exactly do you mean by getting the error "in the Demo2 application"? Does that mean it starts listing packages but when it reaches a line that contains "Demo2" it breaks? I couldn't find "Demo2" anywhere in the list of packages, so am a little confused.

Can you build/run in debug mode and put break-points in and give me more information about where it breaks and perhaps some key variable values?

**Comment by dfilteau** [comment]
> What exactly do you mean by getting the error "in the Demo2 application"? Does that mean it starts listing packages but when it reaches a line that contains "Demo2" it breaks?
When I click on the "Refresh Package List" button it dies immediately.

> I couldn't find "Demo2" anywhere in the list of packages, so am a little confused.
My bad on that.  I'm the one that's confused.  I meant I was running AutoGetItVCL.
 
> Can you build/run in debug mode and put break-points in and give me more information about where it breaks and perhaps some key variable values?
Will do, and thank you for your quick response.

**Comment by dfilteau** [comment]
In debug mode, I'm getting this error when I return from TfrmAutoGetItMain.BDSBinDir in ufrmAutoGetItMain.pas.

![image](https://user-images.githubusercontent.com/13721247/111712453-e4867680-880a-11eb-9540-df4634e627ed.png)

![image](https://user-images.githubusercontent.com/13721247/111712315-9c675400-880a-11eb-8abd-c761317419c0.png)

I'll keep looking.

**Comment by dfilteau** [comment]
Downloading the 10.4.2 update now.  maybe that'll help.

**Comment by dfilteau** [comment]
Nice work, BTW!

**Comment by corneliusdavid** [comment]
Thanks--I've got info for the API and am reworking everything to use the API instead of the command-line.  It'll be MUCH better!

Anyway, the function BDSRootPath looks in the registry to find the RootDir folder for Delphi. Perhaps there's a permissions error?  Or, you mentioned you were running it as admin, perhaps Delphi was installed for a user and the Admin doesn't know about the versions of Delphi so that BDSRootPath is blank!  I didn't test for that...

**Comment by dfilteau** [comment]
I checked the values returned and it looks like it had the correct version (21.0) and the right BIN directory.

I'll update to 10.4.2 and check it again.

**Comment by dfilteau** [comment]
Once I get it working it'll sure save time reinstalling/re-configuring.

**Comment by dfilteau** [comment]
10.4.2 installed.

Win32 error:
![image](https://user-images.githubusercontent.com/13721247/111716086-8a89af00-8812-11eb-8ff6-6fda6b463bf0.png)

Win64 error:
![image](https://user-images.githubusercontent.com/13721247/111716128-9e351580-8812-11eb-8184-ea0dd2d73bc2.png)

I'll try debugging.

**Comment by dfilteau** [comment]
![image](https://user-images.githubusercontent.com/13721247/111716634-b194b080-8813-11eb-94b7-b607a3f4142a.png)
 
So path is retrieved successfully

**Comment by corneliusdavid** [comment]
This is very strange, not sure what to tell you. But I'd look into that "E2029 '(' expected" error in your screen shot--there may be something else messed up in your environment.

**Comment by dfilteau** [comment]
![image](https://user-images.githubusercontent.com/13721247/111732604-19a6bf00-8833-11eb-9894-9b344456dfde.png)

Looks legit but I'll keep looking.
