### ISSUE TITLE
Deleted several packages in 10.3.3

### ISSUE THREAD

**Issue by JFSF** [corneliusdavid/AutoGetIt#5]
Hi.

I've compiled with sucess in Delphi 10.3.3 CE and the GUI does not give any error when running.

However, after selected the packages to install via GetIt the first thing that happens is the deletion of a large number of files. Those files are related to TeeVCL....

**Comment by corneliusdavid** [comment]
AutoGetIt doesn't delete files, it calls GetItCmd commands in an automated fashion, similar to what you would do if you ran it yourself from the command line or ran one of the supplied batch files.  So I would look at the package that was installed to see what it does, not this code.
