### ISSUE TITLE
resolve eol problem in dpr?

### ISSUE THREAD

**Issue by pjrobin** [corneliusdavid/AutoGetIt#7]
As you may know, there are many packages in GetIt that wont work because of a wrong end of line coding (LF instead of CRLF, see https://quality.embarcadero.com/browse/RSP-32976) 

Would it be possible to integrate a routine in AutoGetIt to correct the dpr before installing?

**Comment by corneliusdavid** [comment]
Thank you for your feedback and request but I'm not going to spend the time to address this issue as I'm working on replacing the shelling out to GetItCmd with API calls and completely redoing the interface.
