### ISSUE TITLE
create process error 

### ISSUE THREAD

**Issue by izac3d** [corneliusdavid/AutoGetIt#9]
create process error. what is the problem ?

![Untitled](https://user-images.githubusercontent.com/23438535/127018975-d23833f7-cf1a-4e30-8b60-5a941160572d.jpg)

**Comment by corneliusdavid** [comment]
The error message tells you what the problem is: "_The system cannot find the file specified._" And the file specified is **GetItCmd.exe**. Evidently, GetIt is not in your system path--it should be with a standard install of Delphi.

**Comment by izac3d** [comment]
sorry I am tired and can not concentrate

**Comment by corneliusdavid** [comment]
LOL! No worries!
Thanks for your interest in AutoGetIt. I'm working on a new version that doesn't use the command-line program (see the API branch).

**Comment by izac3d** [comment]
great app.
